export const TamilMonthAPI = ["Chithirai/0",
"Vaikaasi/1",
"Aani/2",
"Aadi/3",
"Aavani/4",
"Purattaasi/5",
"Aippasi/6",
"Karthikai/7",
"Maargazhi/8",
"Thai/9",
"Maasi/10",
"Panguni/11"
]

export const AyanamApi = ["Dakshinayanam/0",
"Uttarayanam/1"
]

export const PaksheApi = ["Krishna/0",
"Sukla/1"]

export const TithiApi = ["Pradhamai/0",
"Dwithiya/1",
"Trithiya/2",
"Chathurthi/3",
"Panchami/4",
"Shashthi/5",
"Sapthami/6",
"Ashtami/7",
"Navami/8",
"Dashami/9",
"Ekadashi/10",
"Dwadashi/11",
"Trayodashi/12",
"Chaturdashi/13",
"Pournami/14",
"Amavasai/15"]

export const NakshatramApi = ["Aswini/0",
"Bharani/1",
"Karthikai/2",
"Rohini/3",
"Mirugaseerisham/4",
"Thiruvathirai/5",
"Punarpoosam/6",
"Poosam/7",
"Ayilyam/8",
"Magam/9",
"Pooram/10",
"Uthiram/11",
"Hastham/12",
"Chithirai/13",
"Swathi/14",
"Visakam/15",
"Anusham/16",
"Kettai/17",
"Moolam/18",
"Pooradam/19",
"Uthiradam/20",
"Tiruvonam/21",
"Avittam/22",
"Sadhayam/23",
"Poorattadhi/24",
"Uthirattadhi/25",
"Revathi/26"]

export const ChandrashtamamApi = ["Ashwini/0",
"Bharani/1",
"Krithika/2",
"Rohini/3",
"Mrigashira/4",
"Ardra/5",
"Punarvasu/6",
"Pushya/7",
"Ashlesha/8",
"Magha/9",
"Purva Phalguni/10",
"Uttara Phalguni/11",
"Hasta/12",
"Chitra/13",
"Swati/14",
"Vishaka/15",
"Anuradha/16",
"Jyeshta/17",
"Mula/18",
"Purva Ashadha/19",
"Uttara Ashadha/20",
"Shravana/21",
"Dhanishta/22",
"Shatabhishak/23",
"Purva Bhadrapada/24",
"Uttara Bhadrapada/25",
"Revati/26"]